### ISSUE TITLE
Undetected chromedriver v2 is deleted all project file

### ISSUE THREAD

**Issue by MateKristof** [ultrafunkamsterdam/undetected-chromedriver#87] opened 2021-01-26 14:51 UTC
**Undetecded chromedriver is deleted all of my project file in the project folder :D** 
Luckily Pycharm local history and github was with me. 

Tested it two time and definitely the UC was that. It happend when I try the new V2 chromedriver. Before this, I use "monkey patch" mode and now I use the "easy, recommend" method. 

In my best of opinion, there is a problem [around this line. ](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/fd16909b89d5265ceaad4757eb1f8dae76a0fa24/undetected_chromedriver/v2.py#L254)

**Comment by MennovDijk** [comment] 2021-01-27 19:36
Same error here, git tracking saved the day but quite painful if all project files are suddenly deleted.

**Comment by HMaker** [comment] 2021-01-28 14:26
@ultrafunkamsterdam I think I found possible places where that bug is
first, [tempfile.gettempdir()](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) may return current working directory;
the `Patcher` may get a chromedriver located in the current working directory [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/v2.py#L126)

**Comment by ultrafunkamsterdam** [comment] 2021-01-29 01:05
> @ultrafunkamsterdam I think I found possible places where that bug is
> first, [tempfile.gettempdir()](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) may return current working directory;
> the `Patcher` may get a chromedriver located in current working directory [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/v2.py#L126), when deleting it [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/v2.py#L449) the current working dir will be deleted too.
> So I suggest paths given by user like `user_data_dir` and `executable_path` in `Chrome` should **not** be removed by the library, remove only paths created by the library, also use random strings to name them.

@HMaker thanks for your input! Did not know tempfile could return the current working directory. However, another problem will arise (i already feel them knocking on the door: "your library causes my harddrive to fill up"). Well, i could see if i can skip removal if a custom path is specified by the user (for whatever reason they need to), and if no custom path is specified it will remove the self-created folders. Good point!

**Comment by ultrafunkamsterdam** [comment] 2021-01-29 01:10
@HMaker , hmm i need to rethink that. Since user_data_dir should be removed to prevent re-use  (dirty profiles might (will) trigger).

**Comment by ultrafunkamsterdam** [comment] 2021-01-29 02:59
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/93

**Comment by HMaker** [comment] 2021-01-29 17:21
> @HMaker , hmm i need to rethink that. Since user_data_dir should be removed to prevent re-use (dirty profiles might (will) trigger).

So it's better to not allow the user to give custom `user_data_dir`. If they give, you can't remove, but if they give an already used it may trigger the antibot measures.

**Comment by HMaker** [comment] 2021-01-29 17:34
> @HMaker thanks for your input! Did not know tempfile could return the current working directory.
@ultrafunkamsterdam I think in that case you are safe because you are creating a subfolder `undetected_chromedriver` [here](tempfile.mkdtemp()), so event if `gettempdir()` return the current working dir, only the subfolder will be deleted.

But I just saw now `executable_path` is by default `./chromedriver` [here](https://github.com/ultrafunkamsterdam/undetected-chromedriver/blob/master/undetected_chromedriver/v2.py#L112), so in fact the `Patcher` will delete the current working dir when that path does not exist or the binary is patched.

**Comment by HMaker** [comment] 2021-01-29 18:09
@ultrafunkamsterdam here are the steps to reproduce that bug
```bash
mkdir -p /tmp/superdir/workingdir
cd /tmp/superdir/workingdir
python -m venv --prompt nukethis venv
source venv/bin/activate
pip install undetected_chromedriver
echo "print('this is me wonderful code, I would not like to have it nuked')" > wonderful_code.py
cat << EOF > nukethis.py
import gc
import undetected_chromedriver.v2 as uc
driver = uc.Chrome()
driver.get('https://httpbin.org')
driver.quit()

# trigger garbage collector, which will call Patcher.__del__()
driver = None
gc.collect()
EOF
```
now running it
```bash
$ ls
nukethis.py  venv  wonderful_code.py
$ python nukethis.py
$ ls wonderful_code.py 2> /dev/null || echo "where is my wonderful code?"
where is my wonderful code?
```

**Comment by ultrafunkamsterdam** [comment] 2021-01-30 21:00
Yes but you did not notice the other change (removal is ..  removed 😏)

**Comment by HMaker** [comment] 2021-01-30 21:28
yeah I see in #93 you removed `Patcher.__del__()`. I just wrote a code to let people know how to reproduce bugs, it's also a proof the bug do exist yet. It makes the bug report complete.

**Comment by ultrafunkamsterdam** [comment] 2021-02-07 08:34
fixed in latest versions

**Closed by ultrafunkamsterdam** 2021-02-07 08:34 UTC
