### ISSUE TITLE
The request could not be satisfied. https://presearch.org/

### ISSUE THREAD

**Issue by quocbaohd** [ultrafunkamsterdam/undetected-chromedriver#655] opened 2022-05-28 03:37 UTC
403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: I_dR-8LPW_X_NMEuH6DcOAwXsxb6jsuDL9Oco-ySNkrjQS4HisHtTQ==

**Comment by sebdelsol** [comment] 2022-05-28 16:39
very probably a duplicate of #646. undetected-chromedriver won't prevent rate limitation and bot behavior detection. 
If you've end up with your IP flagged you'll see those errors a lot.

**Comment by quocbaohd** [comment] 2022-06-02 01:59
Thanks. I will check it again!

**Closed** 2022-06-02 01:59 UTC
