### ISSUE TITLE
Instance of 'Chrome' has no'[insert selenium method]' member pylint(no-member)

### ISSUE THREAD

**Issue by VianneyMI** [ultrafunkamsterdam/undetected-chromedriver#140] opened 2021-04-07 19:32 UTC
For one of my BOT, I updated ,

```
from selenium.webdriver import Chrome
browser = Chrome()
browser.get(url)
```

 by 

```
import undetected_chromedriver as uc
browser = uc.Chrome()
browser.get(url)
```

I get an error from my linter on VS Code saying that the Instance of 'Chrome' has no 'get' member.

It works fine at runtime, I know it's a false positive from my linter but how do I solve this ?

Thanks

**Comment by julionc** [comment] 2021-07-22 20:50
To insert this line at the beginning of a file.

```python
# pylint: disable=maybe-no-member
```

Or create `.pylintrc` file in the root script directory.

```python
[TYPECHECK]
ignored-classes=Chrome
```

Hope this help you. Please, this is not a bug and you should close it.
cc @VianneyMI

**Closed** 2021-08-07 17:27 UTC
